DEBUG = True
SECRET_KEY = 'A0ZrNKFEHUF9*EWFH&*h(H&(#Y(#&HDWDH(/,?RT'

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = r"mysql+pymysql://root:123456@127.0.0.1:3306/book?charset=utf8mb4"

